makelsr.py: fix bad escape in regular expression
Due to Python 3 being pickier with respect to escapes in regular
expressions, makelsr was failing with

   re.error: bad escape \h at position 1 (line 1, column 2)

Fix this using a raw string.