binaries: Fix mingw linking of LilyPond with Guile
Using MinGW-w64 version 11.0.1, linking `lilypond` failed with

```
undefined reference to `BCryptGenRandom'
```

What changed in new versions of MinGW is that it advertises at least Windows
version 7 and thus assumes and links to `-lbcrypt`.

We fix this by pretending that 'libbcrypt' is not available.