book_snippets.py: Fix typos related to `decode`
This commit fixes the following error, which is triggered if there are
problems with `make check`.

```
Traceback (most recent call last):
  File "/home/wl/git/lilypond/scripts/lilypond-book.py", line 803, in <module>
    main()
  File "/home/wl/git/lilypond/scripts/lilypond-book.py", line 785, in main
    do_process_cmd(chunks, global_options)
  File "/home/wl/git/lilypond/scripts/lilypond-book.py", line 475, in do_process_cmd
    do_process_cmd_locked(snippets, options)
  File "/home/wl/git/lilypond/scripts/lilypond-book.py", line 495, in do_process_cmd_locked
    snippet.write_ly()
  File "/home/wl/git/lilypond/python/book_snippets.py", line 1078, in write_ly
    sys.stderr.write(diff_against_existing.decode('utf-8'))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
```