Fix compilation for mingw
GUB reports:
In file included from .../lily/include/lily-guile.hh:26:0,
                 [...]
                 from .../lily/main.cc:39:
.../lily/include/mingw-compatibility.hh:33:15:
error: 'MINGW_INFRINGES_ON_OUR_NAMESPACE_USING_CHAR' does not name a type
 # define CHAR MINGW_INFRINGES_ON_OUR_NAMESPACE_USING_CHAR
               ^
make[1]: *** [out/main.o] Error 1

This seems to be due to the include of lily-guile.hh removed in commit
e1398fd073, pulling in mingw-compatibility.hh. Adding it back (before
windows.h) solves the compilation error, but it could be argued that
having our define earlier just hides the problem and the check should
actually be removed...